<artwork type="asciiart">
struct      = 'struct struct-body

struct-body = '{' struct-line *struct-line '}'

struct-line =  *declaration ';'
            \  *comment
            \  *method
            \  *passThrough
</artwork>
