
int8_t int1;

int8_t intFixed[20];

int8_t  intVar1<>;

int8_t int8Var1<30>;

uint16_t  uint1;

uint16_t uintFixed[20];

uint16_t uintVar1<>;

int32_t uint8Var1<30>;

int8_t int8_t1;

int8_t int8_tFixed[20];

int8_t  int8_tVar1<>;

int8_t int8_tVar2<30>;

uint8_t uint8_t1;

uint8_t uint8_tFixed[20];

uint8_t  uint8_tVar1<>;

uint8_t uint8_tVar2<30>;

int16_t short1;

int16_t shortFixed[20];

int16_t  shortVar1<>;

int16_t shortVar2<30>;

uint15_t ushort1;

int16_t int16_t1;

int16_t int16_tFixed[20];

int16_t  int16_tVar1<>;

int16_t int16_tVar2<30>;

uint16_t uint16_t1;

uint16_t uint16_tFixed[20];

uint16_t  uint16_tVar1<>;

uint16_t uint16_tVar2<30>;

int32_t int32_t1;

int32_t int32_tFixed[20];

int32_t  int32_tVar1<>;

int32_t int32_tVar2<30>;

uint32_t uint32_t1;

uint32_t uint32_tFixed[20];

uint32_t  uint32_tVar1<>;

uint32_t uint32_tVar2<30>;

int64_t int64_t1;

int64_t int64_tFixed[20];

int64_t  int64_tVar1<>;

int64_t Iint64_tar2<30>;

uint64_t uint64_t1;

uint64_t uint64_tFixed[20];

uint64_t  uint64_tVar1<>;

uint64_t uint64_tVar2<30>;

float64_t f64;

float64_t f64A[20];

float64_t f64v<>;

float32_t f32_t;

float32_t f32A[20];

float32_t f32v<>;

float16_t f16_t;

float16_t f16A[20];

float16_t f16v<>;

bool bool1;

bool boolFixed[20];

bool  boolVar1<>;

bool boolVar2<30>;

bool_t bool_t1;

bool_t bool_tFixed[20];

bool_t  bool_tVar1<>;

bool_t bool_tVar2<30>;

string  stringVar1<>;

string stringVar2<30>;
